repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Usa la versión más reciente o la que prefieras
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
